use_frameworks!

platform :ios, '8.0'

target 'XLJShareSDK_Example' do
  pod 'XLJShareSDK', :path => '../'

  target 'XLJShareSDK_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
